apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec: 
      containers:
      - name: web-container
        image: muslumhanozturk/web:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_USER
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_DATABASE_HOST
        resources: {} 
